version: "3.4"

services:
  dbt_console:
    build: .
    volumes:
      - .:/near
    env_file: 
      - .env

  dbt_docs:
    build: .
    volumes:
      - .:/near
    ports:
      - 8080:8080
    expose:
      - 8080
    command: "dbt_docs.sh"
    env_file:
      - .env
