flow:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      role: "{{ env_var('ROLE') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      region: "{{ env_var('REGION') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: SILVER
      threads: 4
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      role: "{{ env_var('ROLE') }}"
      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}"
      region: "{{ env_var('REGION') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: silver
      threads: 4
      client_session_keep_alive: False
