name: dbt_run_scheduled_daily
run-name: dbt_run_scheduled_daily

on:
  workflow_dispatch:
  schedule:
    # Runs 0800 daily (see https://crontab.guru)
    - cron: '0 8 * * *'

env:
  DBT_PROFILES_DIR: ./.github/workflows/.dbt/

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==1.3.0 cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          dbt run-operation run_sp_create_prod_clone
